main: net.plugin.code.OffhandAttack
name: OffhandAttack
version: 1.0.0
author: RÑ‘dginald
api-version: 1.13
api: nu
description: nulll
website: nullll
commands:
  ohatk:
    description: Main command of the plugin.
    usage: /<command>