main: net.plugins.main.RedginaldPlugin
name: RedginaldPlugin
version: 1.0.0
author: RÑ‘dginald
api-version: 1.13
api: idk
description: Some utilities for Wealth server made by me.
website: nulll
commands:
  ohatk:
    description: Manages Offhand Attack functions.
    usage: /<command>
  annihilate:
    description: Empty all containers (or pack animals) in area selected using FAWE.
    usage: /<command>